version: '3'

services:
  app:
    build: .
    volumes:
      - ./src:/app/src
    ports:
      - 8000:8000
    command: poetry run uvicorn src.app:app --reload --host 0.0.0.0
    environment:
      - SLACK_WEBHOOK_URL
      - KIBELA_BASE_URL
      - KIBELA_API_TOKEN
      - SSM_SLACK_WEBHOOK_URL
      - SSM_KIBELA_API_TOKEN
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SECURITY_TOKEN
      - AWS_DEFAULT_REGION
